server:
  port: 8888
  shutdown: graceful
spring:
  lifecycle:
    timeout-per-shutdown-phase: 60
  boot:
    admin:
      monitor:
        status-lifetime: 100000
      ui:
        external-views:
          - label: "ðŸš€"
            url: https://ares
            order: 1000
  security:
    user:
      name: admin
      password: admin
      roles: USER


ares:
  admin:
    username: admin
    password: admin
